

-- Start by joining all tables together  

with t1 as (
    select p.listing_id,
    p.price, 
    p.borough,
    p.neighbourhood,
    p.price_per_month,
    p.latitude,
    p.longitude,
    r.description,
    r.room_type,
    rw.host_name,
    rw.last_review,
    rw.minimum_nights,
    rw.number_of_reviews,
    rw.reviews_per_month,
    rw.calculated_host_listings_count,
    rw.availability_365,
    rw.booked_days_365,
    CASE
        WHEN price >= 0 AND price <= 69 THEN 'Budget'
        WHEN price >= 70 AND price <= 175 THEN 'Average'
        WHEN price >= 175 AND price <= 350 THEN 'Expensive'
        ELSE 'Extravagant'
    END AS price_range
From prices p
FULL JOIN room_types r
ON p.listing_id = r.listing_id
FULL JOIN reviews rw
ON r.listing_id = rw.listing_id)


-- QUESTIONS 

-- What is the most common room type in NYC Airbnb listings?

select 
room_type,
Count(distinct listing_id)
from t1
group by 1
order by 2 desc

-- entire home/apt with 13,266 listings



-- What is the average price of a listing by room type?

select 
room_type,
avg(price)
from t1
group by 1
order by 2 desc

-- entire home/apt     $197.16
-- private room        $81.67
-- shared room         $53.65



-- Which borough has the highest average price per month?

select 
borough,
AVG(price)
from t1
group by 1
order by 2 desc

-- Manhattan   $184.00
-- Brooklyn    $122.00
-- Queens      $92.80
-- Staten I    $86.00  
-- Bronx       $79.20


-- How many listings of each room type are in each borough?

select 
borough,
Count(listing_id)
from t1
group by 1
order by 2 desc

-- Brooklyn        10,460 listings
-- Manhattan       10,322 listings 
-- Queens           3,456 listings 
-- Bronx              697 listings
-- Staten I.          267 listings


-- How many listings in each room type category have a price of over $500 per night?

select 
room_type,
Count(distinct listing_id)
from t1
Where price > 500
Group by 1

-- entire home/apt  395
-- private room      19
-- shared room        1



-- What is the distribution of listing prices by neighborhood?

Select 
    borough,
    MIN(price) as MIN_PRICE,
    MAX(price) as MAX_PRICE,
    AVG(price) as AVG_PRICE
from t1
where borough is not NULL
group by 1
order by 4

-- Borough         MIN_PRICE       MAX_PRICE       AVG_PRICE
-- Bronx           $20.00            $670.00         $79.24
-- Staten Island   $13.00            $300.00         $86.04
-- Queens          $10.00          $2,600.00         $92.81
-- Brooklyn        $10.00          $7,500.00        $121.97
-- Manhattan       $10.00          $5,100.00        $184.00



-- What is the estimated amount of revenue generated by hosts in each borough?

Select 
    borough,
    SUM(price * booked_days_365) as total_revenue
from t1
where borough is not NULL
group by 1

-- Borough             Annual Revenue 
-- Queens                  $58,404,083
-- Brooklyn                $279,130,240
-- Staten Island           $3,443,919
-- Manhattan               $393,420,567
-- Bronx                   $9,324,180



-- What is the average price per month for listings in each neighborhood?

Select 
    neighbourhood,
    room_type,
    AVG(price_per_month) as avg_price
from t1
where neighbourhood is not NULL
group by 1, 2
order by 3 desc

-- Top 3 

-- Sea Gate            $24,485.42
-- Tribeca             $12,066.44
-- Flatiron District   $10,404.19




-- How many listings have no reviews?

select 
neighbourhood,
Count(listing_id)
from t1
where number_of_reviews = 0
group by 1

-- 0
-- all listings have at least 1 review



-- How do the estimated book days correlate with the price of an Airbnb listing in New York City?


Select 
    corr(booked_days_365, price)
from t1

-- Corr 
-- -0.079638
